[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder
extra_scripts = pre:src/build_settings_headers.py